//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.SudokuSolver.Console {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestCaseResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestCaseResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Test.SudokuSolver.Console.TestCaseResources", typeof(TestCaseResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;;;1;2;;;;3
        ///;;2;;;4;;;
        ///;5;;;;;6;;
        ///3;;;7;6;;;4;
        ///;;6;;;8;;;1
        ///;2;;;;;;;7
        ///;;9;;;;;2;
        ///;;;8;;;3;;
        ///1;;;;3;9;;;8.
        /// </summary>
        internal static string TestCase_Medium_1 {
            get {
                return ResourceManager.GetString("TestCase_Medium_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9;;2;;5;;;;
        ///8;;5;;2;;;;
        ///;7;;6;;;;;
        ///;5;;8;;;1;;
        ///;;1;;;;2;;
        ///;;8;;;3;;4;
        ///;;;;;5;;3;
        ///;;;;4;;5;;2
        ///;;;;6;;7;;4.
        /// </summary>
        internal static string TestCase_Super_Svær_1 {
            get {
                return ResourceManager.GetString("TestCase_Super_Svær_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2;;;7;4;;;;
        ///;3;5;;8;;;;
        ///;4;;6;;;;;
        ///5;;8;9;;;;;
        ///6;7;;;;;;8;9
        ///;;;;;6;2;;7
        ///;;;;;2;;3;
        ///;;;;7;;4;2;
        ///;;;;5;9;;;6.
        /// </summary>
        internal static string TestCase_Svær_1 {
            get {
                return ResourceManager.GetString("TestCase_Svær_1", resourceCulture);
            }
        }
    }
}
